### ISSUE TITLE
Add companies using Ruby in Nepal to the site

### ISSUE THREAD

**Issue by amitness** [RubyNepal/rubynepal.github.io#13]
Having such as list will make it easier for those looking for career opportunities in Ruby to apply to these companies.

The idea is to:
- Collect list of companies
- Create a dedicated page on site to list those companies.
- Add a **Companies** text on sidebar of homepage and link it to that page. 

Creating a google form to collect the company info can be a starting step.

What do you think?

**Comment by RohitRox** [comment]
It's a great idea.
I would prefer __Career Oppurtunities__  as the text for the sidebar link

**Comment by amitness** [comment]
@zoras @xecutioner Please have a look. If it sounds good, please create a google form and share it through official social media presence of Ruby / ROR Nepal.

**Comment by zoras** [comment]
Nice thought @amitness. We had previously done the same and listed them in the site. But, most IT companies in Nepal shutdown without knowledge and it's hard to keep it updated so we moved it from the main site to rorh wiki here: https://github.com/RubyNepal/rorh/wiki/Nepalese-Companies-using-Ruby-on-Rails The idea was for companies to be self aware and opt-in but feel free to update the list. 

- We've a dedicated page for Nepali ruby projects in the main site here: https://www.rubynepal.org/made-in-nepal/

- We'll be handing out the Nepali Ruby developers survey soon although most are in Slack/Fb groups.

**Comment by zoras** [comment]
This will be included in the redesign of the rubynepal.org site

**Comment by zoras** [comment]
I'm thinking of adding a page with logos of [Ruby and Rails Companies in Nepal](https://speakerdeck.com/zoras/ruby-developers-nepal?slide=5) like below. 

Also, there should be an option to upload image (& resize to constraint) with valid company website url.

![ruby and rails companies in nepal 001](https://user-images.githubusercontent.com/365783/50754830-23116580-127f-11e9-9c26-6aa647d1a916.jpeg)

**Comment by gkunwar** [comment]
@zoras @RohitRox anyone working on this? If not, I will initiate to work on this. Thoughts ?

**Comment by zoras** [comment]
@gkunwar sure, go ahead 👍

**Comment by RohitRox** [comment]
@gkunwar  👍 🚀 💯   
How are you planning to do it? 
Storybook uses typeform https://storybook.js.org/showcase/ -> https://kq8cfzk7ldy.typeform.com/to/Pxvncl4y?typeform-source=storybook.js.org
Netlify also have a form like that..
Should we do something like that; a self-service form  
Or a regular markdown pull request submission ?

**Comment by gkunwar** [comment]
Thank you @RohitRox for your input. 

In terms of design, I will come up with sketches or low-fidelity feedback mocks. 

To collect companies data, we can use a regular markdown pull request.

Thank you :)
