### ISSUE TITLE
Review and update vulnerabilities dependencies 

### ISSUE THREAD

**Issue by gkunwar** [RubyNepal/rubynepal.github.io#14]

**Comment by gkunwar** [comment]
@zoras Here is PR relate this task:
https://github.com/RubyNepal/rubynepal.github.io/pull/15

**Comment by gkunwar** [comment]
Still we have an issue on brianmario/yajl-ruby gem.
https://github.com/RubyNepal/rubynepal.github.io/network/dependencies

**Comment by zoras** [comment]
Resolved

**Comment by gkunwar** [comment]
:)
