### ISSUE TITLE
Chat and Gallery page doesnot work.

### ISSUE THREAD

**Issue by josisusan** [RubyNepal/rubynepal.github.io#381]
After we deployed https://github.com/RubyNepal/rubynepal.github.io/pull/354, the Chat and Gallery page which reflects to our Slack and Meetup page respectively stopped working.

**Comment by josisusan** [comment]
Is there any reason to not show these social-links?
https://github.com/RubyNepal/rubynepal.github.io/pull/354/files#diff-6ff8b445d373f2b5ae1c6c9abbfa42c4L21-L35
@zoras dai?

**Comment by zoras** [comment]
@josisusan the social links you pointed to are only shown in footer

https://github.com/RubyNepal/rubynepal.github.io/pull/354/files#diff-aeb42283af8ef8e9da40ededd3ae2ab2L29-L30
These two settings are used for Chat and Gallery page
