### ISSUE TITLE
Remove members page

### ISSUE THREAD

**Issue by zoras** [RubyNepal/rubynepal.github.io#4]
As this is an open community we need to remove the members page as the rubyists in Nepal are not limited to the ones shown. Also, it is not possible to update all the time.

Instead allow rubyists to join in the community by filling a form (with a ruby test) which will make them a member of google group mailing list. 
https://groups.google.com/forum/#!forum/ror-nepal

I will enable admin approval in the ror-nepal forum which is now open.

This way we can flow the information or communicate with them more easily when need be.

**Comment by ashishbista** [comment]
I agree with you.
