### ISSUE TITLE
Any plan of video meeting like k8s community meeting

### ISSUE THREAD

**Issue by coolbrg** [RubyNepal/rubynepal.github.io#54]
Hi @zoras ,

Do we  have any plan to meet over once in twice/thrice weeks or month like a Kubernetes community meeting https://github.com/kubernetes/community/tree/master/communication#weekly-meeting

**Comment by zoras** [comment]
Kubernetes is a product oriented community and has a global reach. I don't think this is necessary or practical for us for the time being.
