### ISSUE TITLE
Use jekyll google drive

### ISSUE THREAD

**Issue by brgnepal** [RubyNepal/rubynepal.github.io#62]
I am creating issue solely to start a discussion over the mentioned issue subject and taken from card https://github.com/RubyNepal/rubynepal.github.io/projects/1#card-9467390 with details:

Use jekyll google drive: 
- https://github.com/netlify/jekyll-gdrive
- https://github.com/SimonBiggs/jekyll-google-drive

### My Observations
- Last commit date of above two repos are around 3 years ago
- If we add it, doesn't work then what is our `Plan of Action`?
- If we add it and it works right now but breaks in future versions of Jekyll, what is our plan?

I am just concerned over the cost associated with using any third party dependency.

/cc @zoras

**Comment by zoras** [comment]
FYI, we'll be using netlify forms API for now. https://www.netlify.com/docs/api/#forms
