### ISSUE TITLE
[Question] What is the purpose of /members url?

### ISSUE THREAD

**Issue by coolbrg** [RubyNepal/rubynepal.github.io#63]
Hi,

I am trying to understand the https://rubynepal.org/members/ here.
I went there and added my details and on submitting, I was given message 

![screenshot from 2018-12-12 21-45-32](https://user-images.githubusercontent.com/1132451/49882750-48b17780-fe57-11e8-8ee9-de06c7dd99b3.png)

It would be good if we also show the purpose in the message or link to the purpose of it.
I am surprised that my details are taken but nothing important happened.

**Comment by josisusan** [comment]
The main purpose was to collect the ruby developers info for now. We can later use the info to send out the newsletters/meetup infos.
/cc @zoras

**Comment by coolbrg** [comment]
> The main purpose was to collect the ruby developers info for now. We can later use the info to send out the newsletters/meetup infos.

@josisusan In that case, it would be good to have better UX with conveying message :blush:

**Comment by zoras** [comment]
@josisusan @coolbrg You both are correct.
