### ISSUE TITLE
Add Nepali Language support

### ISSUE THREAD

**Issue by coolbrg** [RubyNepal/rubynepal.github.io#64]
Referencing to the card https://github.com/RubyNepal/rubynepal.github.io/projects/1#card-9363127

This plugin seems to be upto date https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin

rather than

- https://github.com/liamzebedee/jekyll-i18n
- https://github.com/KrzysiekJ/jekyll-i18n_tags

**Comment by jonathanclarke** [comment]
Closing issue.  Language support can be added as a PR if desired.  Feel free to action.
