### ISSUE TITLE
Lets have gems in Project page as well.

### ISSUE THREAD

**Issue by krazedkrish** [RubyNepal/rubynepal.github.io#7]
There are only 3 sites in Made in Nepal section. I am sure the number would increase. But lets also add Gems below the sites. Gems are alos projects but a different section (may be just below sites) in the project  page would be better. 

On showing both sites and gems, RubyNepal will sound more active.

**Comment by zoras** [comment]
@krazedkrish sounds good. Feel free to fork the project and submit a pull request

**Comment by krazedkrish** [comment]
@zoras sure!

**Comment by jonathanclarke** [comment]
Can this issue be closed off? I don't think it was every actioned.
