### ISSUE TITLE
Blog sharing presentation slides/videos of previous meet up.

### ISSUE THREAD

**Issue by krazedkrish** [RubyNepal/rubynepal.github.io#8]
I missed the previous rubynepal meet up. I was hoping to see the sildes or link to sides/videos in the blog. I am sure, there are others like me waiting for it as well.

**Comment by zoras** [comment]
@krazedkrish Not sure how I missed this issue.

See comments section of http://www.meetup.com/Nepal-Ruby-Users-Group/events/224417878/ for slide links of August 9 meetup:

Here's a Recap of the September 13 meetup:

https://www.rubynepal.org/blog/2015/09/24/recap-ruby-meetup-on-september-2015/
