### ISSUE TITLE
Add form to join RubyNepal as a member for free

### ISSUE THREAD

**Issue by zoras** [RubyNepal/rubynepal.github.io#9]
We can add a page in RubyNepal site to collect statistics about Ruby users in Nepal by making them fill-up a google sheet form.

See https://github.com/RubyNepal/rubynepal.github.io/issues/4

> # Remove members page

> As this is an open community we need to remove the members page as the rubyists in Nepal are not limited to the ones shown. Also, it is not possible to update all the time.

> Instead allow rubyists to join in the community by filling a form (with a ruby test) which will make them a member of google group mailing list.
https://groups.google.com/forum/#!forum/ror-nepal

> I will enable admin approval in the ror-nepal forum which is now open.

> This way we can flow the information or communicate with them more easily when need be.

**Comment by zoras** [comment]
Also RubyNepal site cannot be held creditable for the quality and proficiency of the listed member.

**Comment by josisusan** [comment]
working branch: member-page

**Comment by zoras** [comment]
@josisusan do create a PR so we can test directly via netlify deploy site.

**Comment by RohitRox** [comment]
Also,we can use those collected email to send them monthly updates (tech/meetups/jobs) and invitation for upcoming meetups.

**Comment by zoras** [comment]
https://github.com/RubyNepal/rubynepal.github.io/pull/36
